### ISSUE TITLE
Modelagem MongoDb

### ISSUE THREAD

**Issue by JoaoBueno** [JoaoBueno/Estudos-javascript#2]
![image](https://user-images.githubusercontent.com/18366617/28435642-432d91ce-6d6a-11e7-9f09-7964ac483a7f.png)

Neste caso temos:
- Grupos 1:n SubGrupos
- Grupos 1:n Produtos
- SubGrupos 1:n Produtos
- Categorias n:m Produtos

**Dúvida**
Como fazer a modelagem destes, levando em conta que quando for cadastrar um produto eu preciso ver/validar/sugerir os grupos, subgrupos e categorias em forma de select/option ?

**Comment by suissa** [comment]
Primeiramente vamos definir algumas coisas.

1) Os subgrupos só existem dentro do seu Grupo ou eles podem ser reusados? Se 1 subgrupo pode ser usado em MAIS de 1 Grupo por favor exemplifique.

**Comment by suissa** [comment]
2) Um Produto pode ter apenas 1 ou mais Grupos?

3) Um Produto pode ter apenas 1 ou mais SubGrupos?

**Comment by JoaoBueno** [comment]
1. Os SubGrupos estarão em apenas um Grupo.
2. e 3. Os Produtos estarão em apenas um Grupo e SubGrupo.
4. Os Produtos poderão estar em varias Categorias.

Todos os Produtos devem ter no minimo 1 Grupo, 1 SubGrupo e 1 Categoria

**Comment by suissa** [comment]
Com isso já podemos eliminar essa coleção de SubGrupos, pois cada SubGrupo estará dentro de apenas 1 Grupo, caso utilizemos o Mongoose ele irá gerar um _id diferente para cada subgrupo criado/inserido em um Grupo.

Dessa forma você pode linkar apenas o _id do SubGrupo, porém para facilitar as queries é mais interessante colocar o _id tanto do Grupo como do Subgrupo em Produtos.

**Comment by suissa** [comment]
Você também deverá criar um Array de categorias em Produto onde irá apenas adicionar os _ids das Categorias a qual o Produto se encontra.

**Comment by suissa** [comment]
Nesse cenário nós teremos as seguintes coleções:

- produtos;
- grupos;
- categorias.

Onde você irá linkar grupos e categorias em Produtos, porém somente categorias será um Array.

**Comment by JoaoBueno** [comment]
Veja se é isso então:?

const CategoriaSchema = new Schema( {
  codigo: String,
  descricao: String
} )

const GrupoSchema = new Schema( {
  codigo: String,
  descricao: String,
  subGrupo: [{ 
    codigo: String, 
    descricao: String
  }],
} )

const ProdutoSchema = new Schema( {
  codigo: String,
  descricao: String,
  preco: String,
  Grupo: [ { type: Schema.Types.ObjectId, ref: 'Grupo' } ],
  Categoria: [ { type: Schema.Types.ObjectId, ref: 'Categoria' } ]
} )
