### ISSUE TITLE
Chamar uma função atravez de uma variável

### ISSUE THREAD

**Issue by JoaoBueno** [JoaoBueno/Estudos-javascript#3]
Olhe o código abaixo :

`const teste = ( parametro ) => {
  return parametro
}

const funcao = 'teste'

console.log( teste ( 'oi mundao veio' ) ) // este funciona
console.log( funcao ( 'oi mundao veio' ) ) // este não funciona`

Minha pergunta é se existe uma forma de chamar a função teste usando a variável funcao ?

**Comment by suissa** [comment]
Eh pq nessa parte: const funcao = 'teste'

precisa ser const funcao = teste
